#ifndef _GAME_PLAY_SHARED_H_
#define _GAME_PLAY_SHARED_H_

#include "shared.h"

#define GAME_PLAY_GLOBAL_BINDING_GLOBAL_UBO 0
#define GAME_PLAY_GLOBAL_BINDING_VOXEL_HEIGHT_MAP 1
#define GAME_PLAY_GLOBAL_BINDING_TERRAIN_TILE_TINT_MAP 2
#define GAME_PLAY_GLOBAL_BINDING_BILLBOARD_IMAGE_ATLAS 3
#define GAME_PLAY_GLOBAL_BINDING_COLOR_ATTACHMENT_IMAGE 4
#define GAME_PLAY_GLOBAL_BINDING_DEPTH_ATTACHMENT_IMAGE 5

HERO_UNIFORM_BUFFER(GamePlayGlobalUBO, HERO_GFX_DESCRIPTOR_SET_GLOBAL, GAME_PLAY_GLOBAL_BINDING_GLOBAL_UBO) {
	Mat4x4 mvp;
};

#ifdef HERO_GLSL
layout(set = HERO_GFX_DESCRIPTOR_SET_GLOBAL, binding = GAME_PLAY_GLOBAL_BINDING_VOXEL_HEIGHT_MAP, r32f) uniform readonly image2D u_voxel_height_map;
layout(set = HERO_GFX_DESCRIPTOR_SET_GLOBAL, binding = GAME_PLAY_GLOBAL_BINDING_TERRAIN_TILE_TINT_MAP, rgba8) uniform readonly image2D u_terrain_tile_tint_map;

layout(set = HERO_GFX_DESCRIPTOR_SET_GLOBAL, binding = GAME_PLAY_GLOBAL_BINDING_BILLBOARD_IMAGE_ATLAS) uniform sampler2D u_billboard_image_atlas;
#endif

#endif // _GAME_PLAY_SHARED_H_
